### ISSUE TITLE
CLI Build error when changing --output-dir

### ISSUE THREAD

**Issue by benabel** [jtpio/jupyterlite#196]
I forked the github template and adapted for gitlab [here](https://gitlab.com/benabel/jupyterlite-template) . In gitlab pages needs to be in `public` folder.

So I added `--output-dir public` to the jupyter lite build command.

However when building I get this error([Here](https://gitlab.com/benabel/jupyterlite-template/-/jobs/1389163734) is the build log):

```
TaskError - taskid:build:lite:patch:public/jupyter-lite.json
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jupyterlite/addons/base.py", line 180, in merge_one_jupyterlite
    out_path.write_text(
  File "/usr/local/lib/python3.8/pathlib.py", line 1255, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/local/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'public/public/jupyter-lite.json'
```

I get the same error locally while running: `jupyter lite build --files content --output-dir public`, everything works with default ouput dir, here is the diff:

```
diff _output/ public/
Only in _output/: api
Common subdirectories: _output/doc and public/doc
Common subdirectories: _output/files and public/files
diff _output/jupyter-lite.json public/jupyter-lite.json
1a2
>   "jupyter-lite-schema-version": 0,
3d3
<     "appUrl": "./lab",
4a5
>     "appUrl": "./lab",
11,15d11
<     "settingsOverrides": {
<       "@jupyterlab/docmanager-extension:plugin": {
<         "nameFileOnSave": false
<       }
<     },
18,20c14,15
<   },
<   "jupyter-lite-schema-version": 0
< }
\ No newline at end of file
---
>   }
> }
Common subdirectories: _output/kernelspecs and public/kernelspecs
Common subdirectories: _output/lab and public/lab
Common subdirectories: _output/retro and public/retro
Common subdirectories: _output/tree and public/tree
```

The `jupyter-lite.json` isn't copied when changing `output_dir`

**Comment by jtpio** [comment]
By the way if you want to contribute docs for deploying on GitLab Pages, that would be great!

**Comment by benabel** [comment]
@jtpio I'll contribute to the docs when fixed.

Thanks again for this awesome project.
