### ISSUE TITLE
jupyter lite serve may try to use already allocated port

### ISSUE THREAD

**Issue by psychemedia** [jtpio/jupyterlite#208]
If the default port used by `jupyter lite serve` is already allocated, an error will result:

```
[LiteServeApp] WARNING | 

        Serving JupyterLite from:
            /Users/tonyhirst/Documents/GitHub/jupyterlite/examples/_output
        on:
            http://localhost:8000/

        *** Press Ctrl+C to exit **
        
TaskError - taskid:serve:serve:serve
PythonAction Error
Traceback (most recent call last):
  File "/Users/tonyhirst/Library/Python/3.9/lib/python/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jupyterlite/addons/serve.py", line 81, in _serve_tornado
    app.listen(self.port)
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/usr/local/lib/python3.9/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.9/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
```

Ideally, the server should find an unused port and relocate to that,  then announce what port the server is running on.

**Comment by psychemedia** [comment]
There doesn't appear to be an option that allows a use to  specify an alternative (eg `jupyter lite serve --port/-p $PORT`) which would be useful.

**Comment by jtpio** [comment]
Thanks @psychemedia for the report.

> There doesn't appear to be an option that allows a user to specify an alternative port (eg `jupyter lite serve --port/-p $PORT`) which would be useful.

Sounds like this could be added then.
