### ISSUE TITLE
Incorrect path handling: jupyter lite build

### ISSUE THREAD

**Issue by psychemedia** [jtpio/jupyterlite#209]
Trying to make sense of the CLI, I can create a good installation from the current repo using:

```
cd examples
# pwd: repo_root/examples
jupyter lite init --output-dir ../_output2
jupyter lite build --files .  --output-dir ../_output2
```

and all works.
 
But if I try:

```
# pwd: repo_root
jupyter lite init --output-dir _output2
jupyter lite build --files examples  --output-dir _output2
```

I get varying errors along the lines of:

```
Traceback (most recent call last):
  File "$HOME/Library/Python/3.9/lib/python/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jupyterlite/addons/base.py", line 180, in merge_one_jupyterlite
    out_path.write_text(

  ...

FileNotFoundError: [Errno 2] No such file or directory: '$HOME/Documents/GitHub/jupyterlite/_output/examples/jupyter-lite.json'
```

The `examples` directory is actually copied to `$HOME/Documents/GitHub/jupyterlite/_output/files/examples/`.

In some cases, a path element from the previously run command appears in the not found file path? I wonder: is something leaking? Is a `dict` being set as a function parameter somewhere resulting in an incorrect reference being used somewhere else?

**Comment by psychemedia** [comment]
I'm also noticing that the `ipywidgets` demos don't work using the above approach to building a distribution? (i.e. widgets aren't rendered):

![image](https://user-images.githubusercontent.com/82988/124263860-b6177780-db2b-11eb-864a-222d74ab260c.png)

**Comment by jtpio** [comment]
Thanks @psychemedia for the report.

Is `ipywidgets` also installed in the same virtual environment? Then the `@jupyter-widgets/jupyterlab-manager` extension should show up there and be included when running `jupyter lite build`.

**Comment by psychemedia** [comment]
I run the `micropip()` install, the `ipywidgets` package loads with out error.

A complete reproducible example (on my machine!) is:

- clone the repo;
- cd into examples;
- run `jupyter lite init --output-dir ../_output2` && `jupyter lite build --files .  --output-dir ../_output2`
- run `python3 -m http.server 8001 -d _output2` ( I have another service on 8000 so` jupyterlite serve` fails)
- run the widget notebook in Chrome browser.

The widget output is the text, not the HTML widget. I wondered if something was either not being copied over or whether there is actually another bit of setting required in the `examples` dir. Sorry, I have to go now... so very late!

**Comment by jtpio** [comment]
> run `jupyter lite init --output-dir ../_output2` && `jupyter lite build --files . --output-dir ../_output2`

Right before this step, assuming you are in a virtual environment, you should also install `ipywidgets` (for example `pip install ipywidgets`) so it also grabs the lab extension and puts it under `PREFIX/share/jupyter/labextensions`. Then the `jupyter lite build` step should pick up that extension and add it to the `output-dir`, and widgets should show up.

**Comment by bollwyvl** [comment]
Here's the spot in the docs:

https://jupyterlite.readthedocs.io/en/latest/configuring.html#environment-extensions

This section will be expanded upon by #187.

But, yeah, right now the default behavior (no `--federated-extensions` specified) makes that assumption that:
- you _authored_ your notebooks in the same environment in which you install `jupyerlite`
  - _with_ all of the `pip` packages installed that contained the federated extension you needed
  - _and_ a compatible `jupyterlab`

This gives us the benefit of `pip`'s solver, so one might only need to have said `pip install bqplot` to _also_ get `jupyterlab_widgets` from `pip` (and therefore `@jupyter-widgets/jupyterlab-manager`), and see it all properly deployed to  `{lite_dir}/lab/extensions`.

We're looking to deal with this, as well as some other things related to `.whl` files in #151.

Also, regarding the paths: sounds like it might be related to:

- #185
- #200
- #206

But if you can come up with a concrete reproducer, we can put it under test and move  on: this would be good to put to rest.

**Comment by psychemedia** [comment]
Re: reproducing path errors:

```
jupyter lite init
jupyter lite build --files content 
jupyter lite init --output-dir _output999
jupyter lite build --files content  --output-dir _output999
```

results in:

```
...
lite:patch:_output/lab/jupyter-lite.json
.  build:lite:patch:_output/jupyter-lite.json
TaskError - taskid:build:lite:patch:_output/jupyter-lite.json
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jupyterlite/addons/base.py", line 180, in merge_one_jupyterlite
    out_path.write_text(
  File "/usr/local/lib/python3.8/pathlib.py", line 1255, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/local/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/_output999/_output/jupyter-lite.json'
```

**Comment by jtpio** [comment]
@psychemedia is this still an issue?

**Comment by krassowski** [comment]
Still an issue
