### ISSUE TITLE
doit build failed on windows, The system cannot find the file specified

### ISSUE THREAD

**Issue by liudonghua123** [jtpio/jupyterlite#70]
## Description

I followed https://github.com/jtpio/jupyterlite/blob/main/CONTRIBUTING.md, and when I executed `doit`, I got the following errors.

```shell
(common) D:\code\python\jupyterlite>doit list --all --status
R build                  build code and intermediate packages
R build:js:app:classic   build JupyterLite Classic with webpack
R build:js:app:lab       build JupyterLite Lab with webpack
R build:js:lib           build .ts files into .js files
R build:js:pack          build the JupyterLite distribution
U build:py:pyolite       build the pyolite python package for the brower with flit
R docs                   build documentation
R docs:sphinx            build the documentation site with sphinx
R env                    keep environments in sync
R env:binder
R lint                   format and ensure style of code, docs, etc.
R lint:black             format python files with black
R lint:eslint            format and verify .ts, .js files with eslint
R lint:prettier          format .ts, .md, .json, etc. files with prettier
R setup                  perform initial non-python setup
R setup:js               install node packages
R test                   test jupyterlite
R test:js                run the .js, .ts unit tests with jest
R watch                  watch sources and rebuild on change
R watch:docs             watch .md sources and rebuild the documentation
R watch:js               watch .ts, .js, and .css sources and rebuild packages and apps

(common) D:\code\python\jupyterlite>doit
.  lint:black
All done! ✨ 🍰 ✨
7 files would be left unchanged.
.  setup:js
Traceback (most recent call last):
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\cmd_base.py", line 601, in execute
    return self._execute(**exec_params)
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\cmd_run.py", line 264, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\runner.py", line 256, in run_all
    self.run_tasks(task_dispatcher)
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\runner.py", line 222, in run_tasks
    catched_excp = self.execute_task(node.task)
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\runner.py", line 177, in execute_task
    return task.execute(self.stream)
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\task.py", line 460, in execute
    action_return = action.execute(task_stdout, task_stderr)
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\site-packages\doit\action.py", line 216, in execute
    process = subprocess.Popen(
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\liu.d.h\anaconda3\envs\common\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

(common) D:\code\python\jupyterlite>
```

## Expected behavior
Build as expected.

## Context

- Operating System and version: Microsoft Windows [Version 10.0.19042.928]
- Browser and version: Chrome 90
- JupyterLite version: master branch

I can confirm that  I have node/npm/yarn configured correctly. When I executed `yarn build`, it was ok.

```
(common) D:\code\python\jupyterlite>yarn build
yarn run v1.22.10
$ yarn build:lib && yarn build:app
$ lerna run build --scope @jupyterlite/metapackage
lerna notice cli v3.22.1
lerna info versioning independent
lerna info ci enabled
lerna notice filter including "@jupyterlite/metapackage"
lerna info filter [ '@jupyterlite/metapackage' ]
lerna info Executing command in 1 package: "yarn run build"
lerna info run Ran npm script 'build' in '@jupyterlite/metapackage' in 0.9s:
$ tsc -b
lerna success run Ran npm script 'build' in 1 package in 0.9s:
lerna success - @jupyterlite/metapackage
$ lerna run build --stream --parallel --scope "@jupyterlite/app-classic" --scope "@jupyterlite/app-lab"
lerna notice cli v3.22.1
lerna info versioning independent
lerna info ci enabled
lerna notice filter including ["@jupyterlite/app-classic","@jupyterlite/app-lab"]
lerna info filter [ '@jupyterlite/app-classic', '@jupyterlite/app-lab' ]
lerna info Executing command in 2 packages: "yarn run build"
@jupyterlite/app-classic: $ webpack --config ../webpack.config.js
@jupyterlite/app-lab: $ webpack --config ../webpack.config.js
@jupyterlite/app-classic: (node:14312) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\code\python\jupyterlite\node_modules\postcss\package.json.
@jupyterlite/app-classic: Update this package.json to use a subpath pattern like "./*".
@jupyterlite/app-classic: (Use `node --trace-deprecation ...` to show where the warning was created)
@jupyterlite/app-lab: (node:20884) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\code\python\jupyterlite\node_modules\postcss\package.json.
@jupyterlite/app-lab: Update this package.json to use a subpath pattern like "./*".
@jupyterlite/app-lab: (Use `node --trace-deprecation ...` to show where the warning was created)
@jupyterlite/app-classic: assets by path *.js 12.4 MiB
@jupyterlite/app-classic:   assets by chunk 1.69 MiB (id hint: vendors) 8 assets
@jupyterlite/app-classic: assets by chunk 2.79 MiB (auxiliary name: main)
@jupyterlite/app-classic:   assets by path *.svg 1.73 MiB 3 assets
@jupyterlite/app-classic:   assets by path *.eot 363 KiB 3 assets
@jupyterlite/app-classic:   assets by path *.ttf 362 KiB 3 assets
@jupyterlite/app-classic:   assets by path *.woff 203 KiB 3 assets
@jupyterlite/app-classic:   assets by path *.woff2 164 KiB 3 assets
@jupyterlite/app-classic: asset pyolite-0.1.0-py3-none-any.whl 2.91 KiB [compared for emit] [from: ../../packages/pyolite-kernel/py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl]
@jupyterlite/app-classic: orphan modules 116 KiB [orphan] 57 modules
@jupyterlite/app-classic: runtime modules 8.16 KiB 12 modules
@jupyterlite/app-classic: modules by path ../../node_modules/ 10.7 MiB
@jupyterlite/app-classic:   cacheable modules 10.7 MiB 1282 modules
@jupyterlite/app-classic:   3 modules
@jupyterlite/app-classic: modules by path ../../packages/ 97.1 KiB (javascript) 2.91 KiB (asset)
@jupyterlite/app-classic:   javascript modules 94.1 KiB 26 modules
@jupyterlite/app-classic:   asset modules 2.97 KiB (javascript) 2.91 KiB (asset)
@jupyterlite/app-classic:     ../../packages/pyolite-kernel/py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl 42 bytes (javascript) 2.91 KiB (asset) [built] [code generated]
@jupyterlite/app-classic:     ../../packages/pyolite-kernel/lib/worker.js?raw 2.93 KiB [built] [code generated]
@jupyterlite/app-classic: modules by path ./ 6.27 KiB
@jupyterlite/app-classic:   ./index.js 5.11 KiB [built] [code generated]
@jupyterlite/app-classic:   ./build/style.js 1.16 KiB [built] [code generated]
@jupyterlite/app-classic: crypto (ignored) 15 bytes [built] [code generated]
@jupyterlite/app-classic: node-fetch (ignored) 15 bytes [built] [code generated]
@jupyterlite/app-classic: webpack 5.31.2 compiled successfully in 16371 ms
@jupyterlite/app-classic: asset index.css 16.1 KiB [compared for emit] (name: index)
@jupyterlite/app-classic: asset index.js 0 bytes [compared for emit] [minimized] (name: index)
@jupyterlite/app-classic: Entrypoint index 16.1 KiB = index.css 16.1 KiB index.js 0 bytes
@jupyterlite/app-classic: ../../node_modules/@jupyterlab/theme-dark-extension/style/index.css 50 bytes [built] [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-dark-extension/style/variables.css 15.3 KiB [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-dark-extension/style/base.css 472 bytes [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-dark-extension/style/index.css 342 bytes [code generated]
@jupyterlite/app-classic: webpack 5.31.2 compiled successfully in 2307 ms
@jupyterlite/app-classic: asset index.css 15 KiB [compared for emit] (name: index)
@jupyterlite/app-classic: asset index.js 0 bytes [compared for emit] [minimized] (name: index)
@jupyterlite/app-classic: Entrypoint index 15 KiB = index.css 15 KiB index.js 0 bytes
@jupyterlite/app-classic: ../../node_modules/@jupyterlab/theme-light-extension/style/index.css 50 bytes [built] [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-light-extension/style/variables.css 14.2 KiB [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-light-extension/style/base.css 472 bytes [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-light-extension/style/index.css 342 bytes [code generated]
@jupyterlite/app-classic: webpack 5.31.2 compiled successfully in 2302 ms
@jupyterlite/app-classic: asset index.css 21.2 KiB [compared for emit] (name: index)
@jupyterlite/app-classic: asset index.js 0 bytes [compared for emit] [minimized] (name: index)
@jupyterlite/app-classic: Entrypoint index 21.2 KiB = index.css 21.2 KiB index.js 0 bytes
@jupyterlite/app-classic: ../../node_modules/@telamonian/theme-darcula/style/index.css 50 bytes [built] [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@telamonian/theme-darcula/style/codemirror-darcula.css 2.68 KiB [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@telamonian/theme-darcula/style/variables.css 18.1 KiB [code generated]
@jupyterlite/app-classic: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@telamonian/theme-darcula/style/index.css 457 bytes [code generated]
@jupyterlite/app-classic: webpack 5.31.2 compiled successfully in 2301 ms
@jupyterlite/app-lab: assets by path *.js 13.6 MiB
@jupyterlite/app-lab:   assets by chunk 6.67 MiB (id hint: vendors) 41 assets
@jupyterlite/app-lab: assets by chunk 2.79 MiB (auxiliary id hint: vendors)
@jupyterlite/app-lab:   assets by path *.svg 1.73 MiB 3 assets
@jupyterlite/app-lab:   assets by path *.eot 363 KiB 3 assets
@jupyterlite/app-lab:   assets by path *.ttf 362 KiB 3 assets
@jupyterlite/app-lab:   assets by path *.woff 203 KiB
@jupyterlite/app-lab:     asset 9fe5a17c8ab036d20e6c5ba3fd2ac511.woff 99.3 KiB [compared for emit] (auxiliary id hint: vendors)
@jupyterlite/app-lab:     asset 099a9556e1a63ece24f8a99859c94c7d.woff 87.9 KiB [compared for emit] (auxiliary id hint: vendors)
@jupyterlite/app-lab:     asset 7124eb50fc8227c78269f2d995637ff5.woff 15.9 KiB [compared for emit] (auxiliary id hint: vendors)
@jupyterlite/app-lab:   assets by path *.woff2 164 KiB
@jupyterlite/app-lab:     asset e8a427e15cc502bef99cfd722b37ea98.woff2 76.4 KiB [compared for emit] (auxiliary id hint: vendors)
@jupyterlite/app-lab:     asset f7307680c7fe85959f3ecf122493ea7d.woff2 75 KiB [compared for emit] (auxiliary id hint: vendors)
@jupyterlite/app-lab:     asset f0f8230116992e521526097a28f54066.woff2 13 KiB [compared for emit] (auxiliary id hint: vendors)
@jupyterlite/app-lab: asset pyolite-0.1.0-py3-none-any.whl 2.91 KiB [compared for emit] [from: ../../packages/pyolite-kernel/py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl]
@jupyterlite/app-lab: orphan modules 118 KiB [orphan] 60 modules
@jupyterlite/app-lab: runtime modules 8.15 KiB 12 modules
@jupyterlite/app-lab: modules by path ../../node_modules/ 11.5 MiB
@jupyterlite/app-lab:   cacheable modules 11.5 MiB 1393 modules
@jupyterlite/app-lab:   3 modules
@jupyterlite/app-lab: modules by path ../../packages/ 92 KiB (javascript) 2.91 KiB (asset)
@jupyterlite/app-lab:   javascript modules 89.1 KiB 22 modules
@jupyterlite/app-lab:   asset modules 2.97 KiB (javascript) 2.91 KiB (asset)
@jupyterlite/app-lab:     ../../packages/pyolite-kernel/py/pyolite/dist/pyolite-0.1.0-py3-none-any.whl 42 bytes (javascript) 2.91 KiB (asset) [built] [code generated]
@jupyterlite/app-lab:     ../../packages/pyolite-kernel/lib/worker.js?raw 2.93 KiB [built] [code generated]
@jupyterlite/app-lab: modules by path ./ 5.37 KiB
@jupyterlite/app-lab:   ./index.js 3.7 KiB [built] [code generated]
@jupyterlite/app-lab:   ./build/style.js 1.67 KiB [built] [code generated]
@jupyterlite/app-lab: crypto (ignored) 15 bytes [built] [code generated]
@jupyterlite/app-lab: node-fetch (ignored) 15 bytes [built] [code generated]
@jupyterlite/app-lab: webpack 5.31.2 compiled successfully in 17638 ms
@jupyterlite/app-lab: asset index.css 16.1 KiB [compared for emit] (name: index)
@jupyterlite/app-lab: asset index.js 0 bytes [compared for emit] [minimized] (name: index)
@jupyterlite/app-lab: Entrypoint index 16.1 KiB = index.css 16.1 KiB index.js 0 bytes
@jupyterlite/app-lab: ../../node_modules/@jupyterlab/theme-dark-extension/style/index.css 50 bytes [built] [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-dark-extension/style/variables.css 15.3 KiB [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-dark-extension/style/base.css 472 bytes [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-dark-extension/style/index.css 342 bytes [code generated]
@jupyterlite/app-lab: webpack 5.31.2 compiled successfully in 1940 ms
@jupyterlite/app-lab: asset index.css 15 KiB [compared for emit] (name: index)
@jupyterlite/app-lab: asset index.js 0 bytes [compared for emit] [minimized] (name: index)
@jupyterlite/app-lab: Entrypoint index 15 KiB = index.css 15 KiB index.js 0 bytes
@jupyterlite/app-lab: ../../node_modules/@jupyterlab/theme-light-extension/style/index.css 50 bytes [built] [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-light-extension/style/variables.css 14.2 KiB [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-light-extension/style/base.css 472 bytes [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@jupyterlab/theme-light-extension/style/index.css 342 bytes [code generated]
@jupyterlite/app-lab: webpack 5.31.2 compiled successfully in 3042 ms
@jupyterlite/app-lab: asset index.css 21.2 KiB [compared for emit] (name: index)
@jupyterlite/app-lab: asset index.js 0 bytes [compared for emit] [minimized] (name: index)
@jupyterlite/app-lab: Entrypoint index 21.2 KiB = index.css 21.2 KiB index.js 0 bytes
@jupyterlite/app-lab: ../../node_modules/@telamonian/theme-darcula/style/index.css 50 bytes [built] [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@telamonian/theme-darcula/style/codemirror-darcula.css 2.68 KiB [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@telamonian/theme-darcula/style/variables.css 18.1 KiB [code generated]
@jupyterlite/app-lab: css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/@telamonian/theme-darcula/style/index.css 457 bytes [code generated]
@jupyterlite/app-lab: webpack 5.31.2 compiled successfully in 3040 ms
lerna success run Ran npm script 'build' in 2 packages in 21.3s:
lerna success - @jupyterlite/app-classic
lerna success - @jupyterlite/app-lab
Done in 25.85s.

(common) D:\code\python\jupyterlite>ver

Microsoft Windows [Version 10.0.19042.928]

(common) D:\code\python\jupyterlite>
```

**Comment by liudonghua123** [comment]
It seemed the problem was the binary name of `yarn`, If I change all `yarn` with `yarn.cmd`, then it was ok.

Another method to fix is change `shell=False` to `shell=True` in `U.do.CmdAction`.

**Comment by bollwyvl** [comment]
Not `shell=True`, please, but the `yarn` issue is real, and an oversight on my part.

The preferred fix would be:

```python
class P:
    YARN = Path(shutil.which("yarn") or shutil.which("yarn.exe") or shutil.which("yarn.cmd"))
```

and use `P.YARN` throughout.

Note, you may well run into other issues further down the build chain, as node on windows is always... interesting.

**Comment by liudonghua123** [comment]
Why not `shell=True`, It is cleaner, safe, and works as expected. I remembered that I sent a similar pr in dart language. see https://github.com/google/grinder.dart/pull/374/files.

**Comment by bollwyvl** [comment]
In my experience, shell is safe and reliable when you always know exactly
what you're putting into it.

this automation junk is doing long, full absolute paths all over the place,
and it just takes a single `'` to make cmd.exe or pwsh or whatever go ape.

**Comment by liudonghua123** [comment]
Maybe we can add some tests to guarantee `shell=True` works in windows. I used a lot of cross-platform commands in the default shell, and most of the time, it is ok. 
However, both methods have advantages and disadvantages. It is worth using a simple method in the current project.

**Comment by bollwyvl** [comment]
Feel free to try out https://github.com/jtpio/jupyterlite/pull/69 which adds the `which` and path normalizing (for case-sensitive windows systems like _some_ network drives), etc. to `do`. 

Given `shell` has a [Special Considerations](https://docs.python.org/3/library/subprocess.html#security-considerations) section in its official docs, I don't really want to propagate it at the bottom of a build/packaging stack.

Representing Jupyter, we maintain a couple dozen packages and do packaging chores for a couple hundred to keep them all running. Given that visibility, even using approaches that have proven problematic, even once, to users is something we try to avoid. Just hadn't gotten around to firming this flow up for the cross-platform case, as it hasn't even really launched yet, and _definitely_ appreciate bringing it to our attention. :+1:

**Comment by jtpio** [comment]
Thanks @liudonghua123 for reporting, and for the PR!

#69 has been merged, if you want to check it out from `main` directly.

**Comment by liudonghua123** [comment]
> Thanks @liudonghua123 for reporting, and for the PR!
> 
> #69 has been merged, if you want to check it out from `main` directly.

Thanks 😄
